### PR TITLE
add test262 harness

### LINKED ISSUE #8: test262-compliant
Are you interested in being test262-compliant?

### PR DESCRIPTION
**Pull request by longlho**
closes #8 

Right now things fail bc `polyfill.js` is not a fully packaged dist file (test262-harness cannot do `require`)

### CODE REVIEW

**Comment by eemeli** [comment]
Shouldn't this be testing `plural-rules.js` rather than `polyfill.js`? As is, if it's run in an environment with a native `Intl.PluralRules`, it'll run the tests against that rather than the polyfilled version.

**Comment by longlho** [comment]
Test262 assumes Intl.PluralRules being available globally

**Comment by eemeli** [comment]
Then the harness should do something like this:
```js
Intl.PluralRules = require('intl-pluralrules/plural-rules').default
```

**Comment by longlho** [comment]
Right, it just needs a fully packaged dist file w/o any module system.
Should I just add rollup to this?

**Comment by eemeli** [comment]
Sure, let's do that. I've mostly used Webpack, but getting more familiar with Rollup as well might be a good idea.

**Comment by eemeli** [comment]
Closing this, as the codebase has diverged a bit from where it started, and it's been quiet for over a year now.

**Pull request closed without merging**
